# https://wandb.ai
wandb:
  _target_: lightning.pytorch.loggers.WandbLogger

  project: "project_name"
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  save_dir: "${paths.output_dir}"
  log_model: False # "all" or True or False
